### ISSUE TITLE
コメントエラー

### ISSUE THREAD

**Issue by HayatoTenryuu** [miu200521358/vroid2pmx#9]
すみません、このvroid2pmxを使いましたが、このエラーのせいで何も出ませんでした。

■　**CRITICAL**　
■　Vroid2Pmx処理が意図せぬエラーで終了しました。
■　
■　Traceback (most recent call last):
■　  File "service\VroidExportService.py", line 91, in execute
■　  File "service\VroidExportService.py", line 162, in vroid2pmx
■　  File "service\VroidExportService.py", line 147, in vroid2pmx
■　  File "service\VroidExportService.py", line 245, in export_pmxtailor_setting
■　KeyError: 'comment'

使ったモデルは星ノヴァ・ムーナのモデルです。問題はよくわかりませんが、ログファイルはここに入れます。
[Moona.log](https://github.com/miu200521358/vroid2pmx/files/10614160/Moona.log)

よろしくお願いいたします。

**Comment by miu200521358** [comment]
警告に出てるとおり、VRoid Studioから直接出力されたvrmではないため、想定外のvrmになっている可能性があります。

```
■■■■■■■■■■■■■■■■■
■　**WARNING**　
■　VRoid Studio 1.x で出力されたvrmデータではないため、結果がおかしくなる可能性があります。
■　（結果がおかしくてもサポート対象外となります）
■　出力元: saturday06_blender_vrm_exporter_experimental_1.10.0
■■■■■■■■■■■■■■■■■
```
